#include <stdio.h>
#include <stdlib.h>
#include <time.h>

/*
couldve improved

snake dies when it goes to its tail
i probably wouldve make it dont die because when head goes there the tail will be gone
i realized that before uploading so i couldnt done

i wrote same operations twice (not exactly same but very similar)
i could fix it but i wanted to make it more readible with explanations
*/

#define emptyTile -1 // this value represents empty tiles on grid
#define food 0       // this value represents food tiles on grid

int main()
{
    // all variables defined right after program started
    int snake[400][2];      // snake [ cellIndex ] [ 0 ] stores y coordinates of cell and snake [ cell ] [ 1 ] stores x // max size set to 400 cells and 2 values
    int grid[20][20];       // grid[y][x] output grid  (also stores food positions) (max size set to 20)
    unsigned int m, n;      // (grid size m => y , n => x) (unsigned integer) \variables which will taken from player once
    unsigned int foodcount; // (food count) (unsigned integer) \this variable will taken from player once
    char direction = 'n';   // indicates where will snake go. This variable will taken from player every iteration
    int cpx, cpy;           // cp = control point (coordinate) used for storing random points for checking tiles availability
    int snakeLenght = 1;    // stores how long snake become
    int totalMovement = 0;  // stores total movement since start
    int i, j;               // iteration variablees for loops i outer and j inner loop
    int alive = 1;          // checks if player is still alive

    printf("welcome to snake game your goal is to eat all foods with least moves\n");     // tells player what is the goal of the game
    printf("foods are represented with '0' and snake represented by positive numbers\n"); // tells the player what the numbers that will appear on the screen mean
    printf("first let's customize the game a bit\n\n");                                   // notices why player gives input

    do // takes grid size
    {
        printf("height of the grid = ");                         // asks height
        scanf("%d", &m);                                         // takes height of the grid from player
        printf("widht of the grid = ");                          // asks widht
        scanf("%d", &n);                                         // takes widht of the grid from player
        if (n > 20 || m > 20)                                    // if widht or height is bigger than 20
            printf("height and widht cant be bigger than 20\n"); // warn player
    } while (m > 20 || n > 20);                                  // if widht or height is bigger than 20 repeat
    printf("\n");                                                // seperates with next question group

    // takes food count
    do
    {
        printf("number of the food = ");
        scanf("%d", &foodcount);                                                         // takes how many foods will be displayed
        if (foodcount >= (n * m))                                                        // if food count is bigger than grid size we cant display // if its equal there is no space for snake
            printf("number of the foods has to be less than grid size (%d)\n", (n * m)); // we warn player and display total space
    } while (foodcount >= (m * n));                                                      // if food count is equal or bigger than grig size we ask again

    // places food on random positions (random numbers are generated by pseudo number generator.)
    // so we are going to increase randomnes with enterind a seed with srand() function
    srand(time(NULL)); // sets randomizer seed to an integer value returned from time() function (seed = number of seconds elapsed since January 1 1970 00:00:00)

    // gives random x and y values to snakes head
    snake[0][0] = rand() % m; // random y
    snake[0][1] = rand() % n; // random x

    if (foodcount < (m * n) / 2) // i created this if for optimizing. if foods are going to be less than empty tiles we will place food on empty tiles
    {
        // sets all tiles to an empty tile
        for (i = 0; i < m; i++) // for each rows
        {
            for (j = 0; j < n; j++) // for each columns
            {
                grid[i][j] = emptyTile; // set tile on row i and column j as an empty tile
            }
        }

        grid[snake[0][0]][snake[0][1]] = 1; // places snakes head before placing food. because we just want to replace empty tiles with food

        i = 0;                // resets iteration value
        while (i < foodcount) // while placed food is less than the players said // stops if placed food equals to wanted food count
        {
            cpy = rand() % m; // gives an random index value that fits to the grid height and assigns that value to cpy
            cpx = rand() % n; // gives an random index value that fits to the grid widht and assigns that value to cpx

            if (grid[cpy][cpx] == emptyTile) // if control points position on grid is equal to empty tiles value
            {
                grid[cpy][cpx] = food; // places a food on control points position
                i++;                   // placed food value increases
            }                          // if there is alredy a food we will check an another random point
        }
    }
    else /*
            if empty tiles are going to be less or equal to food count instead of placing food place empty tiles on food tiles
            this way when numbers get bigger like with 10000 cells and 9999 program is likely to to try thousands of times only to place last food
            with this extra comparison the most difficult scenario is 1/2
            i duplicated food placement to increase readability else i would only swap variables im open to feedback
         */
    {
        // sets all tiles to a food tile
        for (i = 0; i < m; i++) // for each rows
        {
            for (j = 0; j < n; j++) // for each columns
            {
                grid[i][j] = food; // set tile on row i and column j as a food tile
            }
        }

        grid[snake[0][0]][snake[0][1]] = 1; // places snakes head before placing empty tiles. because we just want to replace foods with empty tiles

        i = 0;                              // resets iteration value
        while (i < (n * m) - foodcount - 1) // while placed empty tile is less than calculated (number of tiles - foodcount -1 (-1 is for snake))
                                            // stops if placed empty tiles equals to what it shoul be
        {
            cpy = rand() % m; // gives an random index value that fits to the grid height and assigns that value to cpy
            cpx = rand() % n; // gives an random index value that fits to the grid widht and assigns that value to cpx

            if (grid[cpy][cpx] == food) // if control points position on grid is equal to a food value
            {
                grid[cpy][cpx] = emptyTile; // places a empty tile on control points position
                i++;                        // placed empty tile value increases
            }                               // if there is alredy a empty tile we will check an another random point
        }
    }
    do
    {
        printf("\n"); // seperates grid from previous output

        for (i = 0; i < m; i++) // for each row
        {
            printf("|");            // row starts with this character
            for (j = 0; j < n; j++) // for each column
            {
                if (grid[i][j] != emptyTile) // if tiles value is not equal to an empty tile
                {
                    printf("%-3d|", grid[i][j]); // reserve 3 space and print '|' character and print value of that tile to the left of the reserved space like '10 |'
                }
                else                    // if value equals to empty tile
                    printf("%4c", '|'); // reserve 4 space and put '|' to the right of the reserved space
            }
            printf("\n\n"); // makes grid more square when widht = hegiht // also seperates info text
        }
        printf("direction: %c   move: %d   foodleft: %d\n", direction, totalMovement, foodcount); // prints info (which way player moved this move | how many moves done since game started | how many foods left)

        // clear last snake cell from grid before we lose coordinates
        grid[snake[snakeLenght - 1][0]][snake[snakeLenght - 1][1]] = emptyTile;

        // each cell moves 1 cell forward
        for (i = snakeLenght; i > 0; i--) // for each cell starting from last cell to first cell except first cell because there is no cell i-1 for i = 0
        {
            snake[i][0] = snake[i - 1][0]; // assigns last y coordinate of cell i-1 to cell i starting from last cell to first cell so we only lose last cells x coordinate
            snake[i][1] = snake[i - 1][1]; // assigns last x coordinate of cell i-1 to cell i starting from last cell to first cell so we only lose last cells x coordinate
        }

        printf("\ncaptain show the way (u,d,l,r)\n"); // asks for direction
        scanf(" %c", &direction);                     // takes direction
        totalMovement++;                              // total movement count increases for every input

        if (direction == 'u') // if direction = u (up)
        {
            snake[0][0]--;       // decrease snakes heads y coordinate because 0 is highest point
            if (snake[0][0] < 0) // if snakes head higher than grid
                alive = 0;       // snake is dead
        }
        else if (direction == 'd') // if direction = d (down)
        {
            snake[0][0]++;        // increase snakes heads y coordinate because lowest poin is m (and its a positive number)
            if (snake[0][0] >= m) // if snakes head is lower than grid
                alive = 0;        // snake is dead
        }
        else if (direction == 'l') // if direction = l (left)
        {
            snake[0][1]--;       // decrease snakes heads x coordinate
            if (snake[0][1] < 0) // if the snakes head sticks out from the left side of the board
                alive = 0;       // snake is dead
        }
        else if (direction == 'r')
        {
            snake[0][1]++;        // increase snakes heads x coordinate
            if (snake[0][1] >= n) // if the snakes head sticks out from the right side of the board
                alive = 0;        // snake is dead
        }

        // checks if snake bites itself
        for (i = 1; i < snakeLenght; i++)                                 // for each cell
            if (snake[0][0] == snake[i][0] && snake[0][1] == snake[i][1]) // if snakes heads has same x and y value with cell i
                alive = 0;                                                // snake is dead

        // if snake eats food it grows
        if (grid[snake[0][0]][snake[0][1]] == food) // if snakes head is on food
        {
            snake[snakeLenght][0] = snake[snakeLenght - 1][0]; // sets y value of new cell
            snake[snakeLenght][1] = snake[snakeLenght - 1][1]; // sets x value of new cell
            snakeLenght++;                                     // increases snake lenght for operations
            foodcount--;                                       // one food has eaten
        }

        // places new snake on grid
        for (i = snakeLenght - 1; i >= 0; i--) // for each cell
        {
            grid[snake[i][0]][snake[i][1]] = i + 1; // places cells number (index +) on the grid
        }
    } while (alive && foodcount); // if snake is dead or food runs out game is over

    // print the last iteration of the grid
    for (i = 0; i < m; i++) // for each row
    {
        printf("|");            // each row starts with '|'
        for (j = 0; j < n; j++) // for each column
        {
            if (grid[i][j] != emptyTile) // if tiles value is not equal to an empty tile
            {
                printf("%-3d|", grid[i][j]); // reserve 3 space and print '|' character and print value of that tile to the left of the reserved space like '10 |'
            }
            else                    // if value equals to empty tile
                printf("%4c", '|'); // reserve 4 space and put '|' to the right of the reserved space
        }
        printf("\n\n"); // seperates final message
    }

    if (!foodcount)                                                                                 // if food runs out
        printf("congratulations! You have reached the max lengt in %d moves\n\n\n", totalMovement); // prints victory message

    if (!alive)                 // if snake is dead
        printf("Dead End\n\n"); // prints loss message

    scanf(" %c"); // stops terminal from closing so player can read last message

    return 0; // program ends
}
